### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by sannesofie** [lab-antwerp-1/fantastic-four#3]
- Setup: GitHub
  - [ ] created this issue
  - [ ] assigned myself
  - [ ] moved the issue to the project board
- Setup: local
  - [ ] pulled the most recent code from `main`/`master`
  - [ ] created a new branch for my introduction
- Writing the content:
  - [ ] added my intro file in `/people` according to group conventions
  - [ ] linked to my file from `/README.md` according to group conventions
- Before pushing my branch:
  - [ ] formatted the code
  - [ ] fixed all spelling mistakes and added new words to the dictionary
  - [ ] fixed all linting mistakes
- After pushing my branch:
  - [ ] created a new PR linked to this issue
  - [ ] make sure all of the checks passed
  - [ ] assigned someone to review and merge my PR

**Comment by colevandersWands** [comment]
@sannesofie, you'll want to add this checklist in the description of the Pull Request you create when you add your introduction file to the repo.  This will be a checklist to make sure you've completed all the steps before asking someone to review your PR.

Easy mistake to make, no worries!  You can close this issue and create a new PR with this checklist once you've pushed your branch.
